FROM node:alpine as build

WORKDIR /app
COPY ui/package.json ui/package-lock.json ./
RUN npm ci

COPY ui ./
RUN npm run build
RUN ls -la
RUN echo "BUILD COMPLETE"

FROM scratch as artifact
COPY --from=build /app/build /build
